from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastro(object):
    def setupUi(self, MainWindow_cadastro):
        MainWindow_cadastro.setObjectName("MainWindow_cadastro")
        MainWindow_cadastro.setWindowModality(QtCore.Qt.NonModal)
        MainWindow_cadastro.resize(1220, 892)
        MainWindow_cadastro.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow_cadastro.setMouseTracking(False)
        MainWindow_cadastro.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow_cadastro.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow_cadastro.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow_cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_principal_cadastro = QtWidgets.QFrame(self.centralwidget)
        self.frame_principal_cadastro.setGeometry(QtCore.QRect(0, 0, 1221, 851))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_principal_cadastro.sizePolicy().hasHeightForWidth())
        self.frame_principal_cadastro.setSizePolicy(sizePolicy)
        self.frame_principal_cadastro.setMinimumSize(QtCore.QSize(1221, 851))
        self.frame_principal_cadastro.setMaximumSize(QtCore.QSize(1221, 851))
        self.frame_principal_cadastro.setStyleSheet("background-color: rgb(0, 191, 99);\n"
"border:20px solid rgb(5, 122, 58);\n"
"")
        self.frame_principal_cadastro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal_cadastro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal_cadastro.setObjectName("frame_principal_cadastro")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_principal_cadastro)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(321, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(321, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_principal_cadastro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(461, 71))
        self.frame_3.setMaximumSize(QtCore.QSize(461, 71))
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setStyleSheet("background-color: rgb(5, 122, 58);\n"
"border-radius:20px;\n"
"color:white;\n"
"border:0px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_controlepatrimonio = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_controlepatrimonio.sizePolicy().hasHeightForWidth())
        self.label_controlepatrimonio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_controlepatrimonio.setFont(font)
        self.label_controlepatrimonio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_controlepatrimonio.setStyleSheet("font: 32pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(5, 122, 58);")
        self.label_controlepatrimonio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_controlepatrimonio.setObjectName("label_controlepatrimonio")
        self.horizontalLayout_2.addWidget(self.label_controlepatrimonio)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_verde = QtWidgets.QFrame(self.frame_principal_cadastro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_verde.sizePolicy().hasHeightForWidth())
        self.frame_verde.setSizePolicy(sizePolicy)
        self.frame_verde.setMinimumSize(QtCore.QSize(1121, 681))
        self.frame_verde.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-width:40px;")
        self.frame_verde.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_verde.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_verde.setObjectName("frame_verde")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_verde)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_cadastro_5 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_5.setMinimumSize(QtCore.QSize(145, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_5.setFont(font)
        self.label_cadastro_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_5.setStyleSheet("border:0px;\n"
"")
        self.label_cadastro_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_5.setObjectName("label_cadastro_5")
        self.horizontalLayout_6.addWidget(self.label_cadastro_5)
        self.lineEdit_cadastro_id = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_id.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_id.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_id.setObjectName("lineEdit_cadastro_id")
        self.horizontalLayout_6.addWidget(self.lineEdit_cadastro_id)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_cadastro_3 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_3.setMinimumSize(QtCore.QSize(81, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_3.setFont(font)
        self.label_cadastro_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_3.setStyleSheet("border:0px;\n"
"")
        self.label_cadastro_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_3.setObjectName("label_cadastro_3")
        self.horizontalLayout_4.addWidget(self.label_cadastro_3)
        self.lineEdit_cadastro_nome = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_nome.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_nome.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_nome.setObjectName("lineEdit_cadastro_nome")
        self.horizontalLayout_4.addWidget(self.lineEdit_cadastro_nome)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_cadastro_4 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_4.setMinimumSize(QtCore.QSize(145, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_4.setFont(font)
        self.label_cadastro_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_4.setStyleSheet("border:0px;\n"
"")
        self.label_cadastro_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_4.setObjectName("label_cadastro_4")
        self.horizontalLayout_5.addWidget(self.label_cadastro_4)
        self.lineEdit_cadastro_grupo = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_grupo.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_grupo.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_grupo.setObjectName("lineEdit_cadastro_grupo")
        self.horizontalLayout_5.addWidget(self.lineEdit_cadastro_grupo)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cadastro = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro.setMinimumSize(QtCore.QSize(145, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro.setFont(font)
        self.label_cadastro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro.setStyleSheet("border:0px;\n"
"")
        self.label_cadastro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro.setObjectName("label_cadastro")
        self.horizontalLayout.addWidget(self.label_cadastro)
        self.lineEdit_cadastro_descricao = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_descricao.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_descricao.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_descricao.setObjectName("lineEdit_cadastro_descricao")
        self.horizontalLayout.addWidget(self.lineEdit_cadastro_descricao)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_cadastro_2 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_2.setMinimumSize(QtCore.QSize(145, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_2.setFont(font)
        self.label_cadastro_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_2.setStyleSheet("border:0px;")
        self.label_cadastro_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_2.setObjectName("label_cadastro_2")
        self.horizontalLayout_3.addWidget(self.label_cadastro_2)
        self.lineEdit_cadastro_nSerie = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_nSerie.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_nSerie.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_nSerie.setObjectName("lineEdit_cadastro_nSerie")
        self.horizontalLayout_3.addWidget(self.lineEdit_cadastro_nSerie)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_cadastro_10 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_10.setMinimumSize(QtCore.QSize(145, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_10.setFont(font)
        self.label_cadastro_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_10.setStyleSheet("border:0px;")
        self.label_cadastro_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_10.setObjectName("label_cadastro_10")
        self.horizontalLayout_11.addWidget(self.label_cadastro_10)
        self.lineEdit_cadastro_dAquisicao = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_dAquisicao.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_dAquisicao.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_dAquisicao.setObjectName("lineEdit_cadastro_dAquisicao")
        self.horizontalLayout_11.addWidget(self.lineEdit_cadastro_dAquisicao)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_cadastro_7 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_7.setMinimumSize(QtCore.QSize(146, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_7.setFont(font)
        self.label_cadastro_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_7.setStyleSheet("border:0px;")
        self.label_cadastro_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_7.setObjectName("label_cadastro_7")
        self.horizontalLayout_8.addWidget(self.label_cadastro_7)
        self.lineEdit_cadastro_vAquisicao = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_vAquisicao.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_vAquisicao.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_vAquisicao.setObjectName("lineEdit_cadastro_vAquisicao")
        self.horizontalLayout_8.addWidget(self.lineEdit_cadastro_vAquisicao)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_cadastro_6 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_6.setMinimumSize(QtCore.QSize(152, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_6.setFont(font)
        self.label_cadastro_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_6.setStyleSheet("border:0px;")
        self.label_cadastro_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_6.setObjectName("label_cadastro_6")
        self.horizontalLayout_7.addWidget(self.label_cadastro_6)
        self.lineEdit_cadastro_vida = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_vida.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_vida.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_vida.setObjectName("lineEdit_cadastro_vida")
        self.horizontalLayout_7.addWidget(self.lineEdit_cadastro_vida)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_cadastro_8 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_8.setMinimumSize(QtCore.QSize(152, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_8.setFont(font)
        self.label_cadastro_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_8.setStyleSheet("border:0px;")
        self.label_cadastro_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_8.setObjectName("label_cadastro_8")
        self.horizontalLayout_9.addWidget(self.label_cadastro_8)
        self.lineEdit_cadastro_local = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_local.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_local.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_local.setObjectName("lineEdit_cadastro_local")
        self.horizontalLayout_9.addWidget(self.lineEdit_cadastro_local)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_cadastro_9 = QtWidgets.QLabel(self.frame_verde)
        self.label_cadastro_9.setMinimumSize(QtCore.QSize(153, 62))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_cadastro_9.setFont(font)
        self.label_cadastro_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cadastro_9.setStyleSheet("border:0px;")
        self.label_cadastro_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro_9.setObjectName("label_cadastro_9")
        self.horizontalLayout_10.addWidget(self.label_cadastro_9)
        self.lineEdit_cadastro_nota = QtWidgets.QLineEdit(self.frame_verde)
        self.lineEdit_cadastro_nota.setMinimumSize(QtCore.QSize(251, 41))
        self.lineEdit_cadastro_nota.setStyleSheet("background-color: rgb(233, 227, 227);\n"
"border:2px solid rgb(165, 160, 160);")
        self.lineEdit_cadastro_nota.setObjectName("lineEdit_cadastro_nota")
        self.horizontalLayout_10.addWidget(self.lineEdit_cadastro_nota)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.btn_limpar = QtWidgets.QPushButton(self.frame_verde)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_limpar.sizePolicy().hasHeightForWidth())
        self.btn_limpar.setSizePolicy(sizePolicy)
        self.btn_limpar.setMinimumSize(QtCore.QSize(361, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_limpar.setFont(font)
        self.btn_limpar.setStyleSheet("QPushButton {\n"
"background-color: rgb(5, 122, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(5, 150, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(5, 122, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}")
        self.btn_limpar.setObjectName("btn_limpar")
        self.horizontalLayout_13.addWidget(self.btn_limpar)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.btn_salvar = QtWidgets.QPushButton(self.frame_verde)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salvar.sizePolicy().hasHeightForWidth())
        self.btn_salvar.setSizePolicy(sizePolicy)
        self.btn_salvar.setMinimumSize(QtCore.QSize(361, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_salvar.setFont(font)
        self.btn_salvar.setStyleSheet("QPushButton {\n"
"background-color: rgb(5, 122, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(5, 150, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(5, 122, 58);\n"
"color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:black;\n"
"border-radius:20px;\n"
"}")
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout_13.addWidget(self.btn_salvar)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.gridLayout.addWidget(self.frame_verde, 1, 1, 2, 3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        MainWindow_cadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_cadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_cadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_cadastro)
        self.statusbar.setObjectName("statusbar")
        MainWindow_cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_cadastro)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_cadastro)

    def retranslateUi(self, MainWindow_cadastro):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_cadastro.setWindowTitle(_translate("MainWindow_cadastro", "MainWindow"))
        self.label_controlepatrimonio.setText(_translate("MainWindow_cadastro", "Controle de Patrimônio"))
        self.label_cadastro_5.setText(_translate("MainWindow_cadastro", "Código"))
        self.label_cadastro_3.setText(_translate("MainWindow_cadastro", "Nome do Item"))
        self.label_cadastro_4.setText(_translate("MainWindow_cadastro", "Grupo"))
        self.label_cadastro.setText(_translate("MainWindow_cadastro", "Descrição"))
        self.label_cadastro_2.setText(_translate("MainWindow_cadastro", "N° de Série"))
        self.label_cadastro_10.setText(_translate("MainWindow_cadastro", "Data Aquisição"))
        self.label_cadastro_7.setText(_translate("MainWindow_cadastro", "Valor Aquisição"))
        self.label_cadastro_6.setText(_translate("MainWindow_cadastro", "Vida Útil"))
        self.label_cadastro_8.setText(_translate("MainWindow_cadastro", "Localização"))
        self.label_cadastro_9.setText(_translate("MainWindow_cadastro", "Nota Fiscal"))
        self.btn_limpar.setText(_translate("MainWindow_cadastro", "Limpar"))
        self.btn_salvar.setText(_translate("MainWindow_cadastro", "Salvar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_cadastro = QtWidgets.QMainWindow()
    ui = Ui_cadastro()
    ui.setupUi(MainWindow_cadastro)
    MainWindow_cadastro.show()
    sys.exit(app.exec_())
