# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 842)
        MainWindow.setStyleSheet("background-color: rgb(255, 248, 248);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_barraLateral_ICONS = QtWidgets.QFrame(self.centralwidget)
        self.frame_barraLateral_ICONS.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame_barraLateral_ICONS.setStyleSheet("background-color: rgb(0, 191, 99);")
        self.frame_barraLateral_ICONS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_barraLateral_ICONS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_barraLateral_ICONS.setObjectName("frame_barraLateral_ICONS")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_barraLateral_ICONS)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 80px 100px;\n"
"    border: none\n"
"}")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/logo__ideau.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2.addWidget(self.frame_11, 0, QtCore.Qt.AlignBottom)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_barraLateral_ICONS)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 48px 48px; /* Ajuste o tamanho conforme necessário */\n"
"    border: none\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"background-color:#057A3A; \n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignVCenter)
        self.frame_12 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2.addWidget(self.frame_12)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_barraLateral_ICONS)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 40px 48px; \n"
"    border: none\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"background-color:#057A3A; \n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/mala.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.frame_13 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_2.addWidget(self.frame_13)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_barraLateral_ICONS)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 48px 48px; \n"
"    border: none\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"background-color:#057A3A; \n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/sem o fundo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.frame_9 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_barraLateral_ICONS)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 38px 48px; \n"
"    border: none\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"background-color:#057A3A; \n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.frame_barraLateral_ICONS)
        self.frame_barraLateral = QtWidgets.QFrame(self.centralwidget)
        self.frame_barraLateral.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frame_barraLateral.setStyleSheet("background-color: rgb(0, 191, 99);\n"
"    border-top-right-radius: 30px;\n"
"    border-bottom-right-radius: 30px;")
        self.frame_barraLateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_barraLateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_barraLateral.setObjectName("frame_barraLateral")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_barraLateral)
        self.verticalLayout_17.setContentsMargins(38, -1, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_17 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 100px 100px;\n"
"    border: none\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_13.addWidget(self.pushButton_10, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_17.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_15.setContentsMargins(16, -1, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_17.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    color:rgb(0, 85, 0);\n"
"    qproperty-iconSize: 38px 38px; \n"
"    border-radius: 15px;\n"
"    padding-right:15px;\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QPushButton { \n"
"    border: 4px solid rgb(0, 85, 0);\n"
"    font-size:23px;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_16.addWidget(self.pushButton_9)
        self.frame_29 = QtWidgets.QFrame(self.frame_21)
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_16.addWidget(self.frame_29)
        self.frame_14 = QtWidgets.QFrame(self.frame_21)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_16.addWidget(self.frame_14)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    color: rgb(226, 226, 226);\n"
"\n"
"    qproperty-iconSize: 28px 38px; \n"
"    border-radius: 15px;\n"
"    padding-right:10px;\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QPushButton {  color:rgb(0, 85, 0);    \n"
"    border: 4px solid rgb(0, 85, 0);\n"
"    font-size:23px;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}\n"
"")
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_16.addWidget(self.pushButton_8)
        self.frame_30 = QtWidgets.QFrame(self.frame_21)
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_16.addWidget(self.frame_30)
        self.frame_16 = QtWidgets.QFrame(self.frame_21)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_16.addWidget(self.frame_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    color:rgb(0, 85, 0);\n"
"    qproperty-iconSize: 28px 38px; \n"
"    border-radius: 15px;\n"
"    padding-right:15px;\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QPushButton { \n"
"    border: 4px solid rgb(0, 85, 0);\n"
"    font-size:23px;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_16.addWidget(self.pushButton_7)
        self.verticalLayout_17.addWidget(self.frame_21, 0, QtCore.Qt.AlignLeft)
        self.frame_18 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_17.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_17.addWidget(self.frame_19)
        self.frame_15 = QtWidgets.QFrame(self.frame_barraLateral)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    color:rgb(0, 85, 0);\n"
"    qproperty-iconSize: 30px 38px; \n"
"    border-radius: 15px;\n"
"    padding-right:15px;\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QPushButton { \n"
"    border: 4px solid rgb(0, 85, 0);\n"
"    font-size:23px;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_11.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_17.addWidget(self.frame_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.frame_barraLateral)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("background-color: rgb(255, 248, 248);")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_main)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_22 = QtWidgets.QFrame(self.frame_5)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 38px 48px; /* Ajuste o tamanho conforme necessário */\n"
"    border: none\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"}")
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_18.addWidget(self.pushButton_11, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.frame_22)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_3.addWidget(self.frame_26)
        self.horizontalLayout_2.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_5)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_2.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_5)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_28 = QtWidgets.QFrame(self.frame_24)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_4.addWidget(self.frame_28)
        self.frame_27 = QtWidgets.QFrame(self.frame_24)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    qproperty-iconSize: 70px 55px; /* Ajuste o tamanho conforme necessário */\n"
"    border: none\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-radius:30px;\n"
"color:white;\n"
" padding-left:5px;\n"
"  padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:30px;\n"
" padding-top: 7px;\n"
" padding-left:7px;\n"
"}")
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/imagens/meuperfil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.frame_27)
        self.horizontalLayout_2.addWidget(self.frame_24)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_main)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(360, 240, 201, 151))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(290, 220, 271, 221))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(230, 240, 401, 241))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_19.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.pushButton_11.toggled['bool'].connect(self.frame_barraLateral_ICONS.setHidden)
        self.pushButton_11.toggled['bool'].connect(self.frame_barraLateral.setVisible)
        self.pushButton_4.toggled['bool'].connect(self.pushButton_9.setChecked)
        self.pushButton_2.toggled['bool'].connect(self.pushButton_8.setChecked)
        self.pushButton_6.pressed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_9.setText(_translate("MainWindow", "Usuários"))
        self.pushButton_8.setText(_translate("MainWindow", "Patrimônio"))
        self.pushButton_7.setText(_translate("MainWindow", "Meu perfil"))
        self.pushButton_6.setText(_translate("MainWindow", "Sair"))
        self.label.setText(_translate("MainWindow", "USUARIOS"))
        self.label_2.setText(_translate("MainWindow", "patrimonio"))
        self.label_3.setText(_translate("MainWindow", "MEu perfil"))
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
