# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meu_perfl.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("\n"
"QFrame {\n"
"    \n"
"    \n"
"    background-image: url(:/newPrefix/imagens/fundo_meuperfil.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-position: center;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 500))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setMaximumSize(QtCore.QSize(215, 16777215))
        self.widget_9.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_23 = QtWidgets.QWidget(self.widget_9)
        self.widget_23.setStyleSheet("background:0;\n"
"border: 0px;")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setStyleSheet("color:rgb(5, 122, 58);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.gridLayout_2.addWidget(self.widget_23, 2, 0, 1, 3)
        self.widget_27 = QtWidgets.QWidget(self.widget_9)
        self.widget_27.setMaximumSize(QtCore.QSize(30, 100))
        self.widget_27.setStyleSheet("border: 0px;\n"
"background: 0")
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_2.addWidget(self.widget_27, 0, 2, 1, 1)
        self.widget_22 = QtWidgets.QWidget(self.widget_9)
        self.widget_22.setStyleSheet("background:0;\n"
"border: 0px;")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setStyleSheet("color:rgb(5, 122, 58);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.gridLayout_2.addWidget(self.widget_22, 1, 0, 1, 3)
        self.widget_21 = QtWidgets.QWidget(self.widget_9)
        self.widget_21.setMaximumSize(QtCore.QSize(30, 100))
        self.widget_21.setStyleSheet("border: 0px;\n"
"background: 0")
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_2.addWidget(self.widget_21, 0, 0, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.widget_9)
        self.widget_19.setMaximumSize(QtCore.QSize(100, 100))
        self.widget_19.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);\n"
"border: 0px")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_19)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/imagens/logo__ideau.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.widget_19, 0, 1, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.widget_9)
        self.widget_24.setStyleSheet("background:0;\n"
"border: 0px;")
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setStyleSheet("color:rgb(5, 122, 58);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.gridLayout_2.addWidget(self.widget_24, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_9, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.widget_3.setObjectName("widget_3")
        self.widget_30 = QtWidgets.QWidget(self.widget_3)
        self.widget_30.setGeometry(QtCore.QRect(0, 140, 131, 12))
        self.widget_30.setMaximumSize(QtCore.QSize(400, 12))
        self.widget_30.setStyleSheet("background-color:rgb(5, 122, 58);")
        self.widget_30.setObjectName("widget_30")
        self.widget_31 = QtWidgets.QWidget(self.widget_3)
        self.widget_31.setGeometry(QtCore.QRect(0, 160, 300, 12))
        self.widget_31.setMaximumSize(QtCore.QSize(300, 12))
        self.widget_31.setStyleSheet("background-color:rgb(5, 122, 58);")
        self.widget_31.setObjectName("widget_31")
        self.widget_32 = QtWidgets.QWidget(self.widget_31)
        self.widget_32.setGeometry(QtCore.QRect(0, 0, 300, 12))
        self.widget_32.setMaximumSize(QtCore.QSize(300, 12))
        self.widget_32.setStyleSheet("background-color:rgb(5, 122, 58);")
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.frame)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_15 = QtWidgets.QWidget(self.widget_4)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_15.setObjectName("widget_15")
        self.widget_28 = QtWidgets.QWidget(self.widget_15)
        self.widget_28.setGeometry(QtCore.QRect(290, 30, 273, 12))
        self.widget_28.setMaximumSize(QtCore.QSize(300, 12))
        self.widget_28.setStyleSheet("background-color:rgb(5, 122, 58);")
        self.widget_28.setObjectName("widget_28")
        self.widget_29 = QtWidgets.QWidget(self.widget_15)
        self.widget_29.setGeometry(QtCore.QRect(160, 10, 400, 12))
        self.widget_29.setMaximumSize(QtCore.QSize(400, 12))
        self.widget_29.setStyleSheet("background-color:rgb(5, 122, 58);")
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_3.addWidget(self.widget_15)
        self.widget_13 = QtWidgets.QWidget(self.widget_4)
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_13.setObjectName("widget_13")
        self.pushButton = QtWidgets.QPushButton(self.widget_13)
        self.pushButton.setGeometry(QtCore.QRect(30, 25, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    color:rgb(5, 122, 58);\n"
"    border: 2px solid rgb(5, 122, 58);\n"
"}\n"
"QPushButton:hover{background-color:rgba(5, 122, 58,150);color:white; border: 2px solid rgb(255, 255, 255)}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.widget_13)
        self.widget_10 = QtWidgets.QWidget(self.widget_4)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_16 = QtWidgets.QWidget(self.widget_10)
        self.widget_16.setMaximumSize(QtCore.QSize(700, 121))
        self.widget_16.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);")
        self.widget_16.setObjectName("widget_16")
        self.label_6 = QtWidgets.QLabel(self.widget_16)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_16)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_16)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.widget_16)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_14 = QtWidgets.QWidget(self.widget_4)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_17 = QtWidgets.QWidget(self.widget_14)
        self.widget_17.setMaximumSize(QtCore.QSize(700, 80))
        self.widget_17.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);")
        self.widget_17.setObjectName("widget_17")
        self.label_9 = QtWidgets.QLabel(self.widget_17)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_17)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.widget_17)
        self.verticalLayout_3.addWidget(self.widget_14)
        self.widget_11 = QtWidgets.QWidget(self.widget_4)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_18 = QtWidgets.QWidget(self.widget_11)
        self.widget_18.setMaximumSize(QtCore.QSize(700, 16777215))
        self.widget_18.setStyleSheet("background-color: rgba(255, 255, 255, 150);\n"
"border-radius:30px;\n"
"border: 1px solid rgb(0, 191, 99);")
        self.widget_18.setObjectName("widget_18")
        self.label_11 = QtWidgets.QLabel(self.widget_18)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_18)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_18)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background:0;\n"
"color: rgb(5, 122, 58);\n"
"border:0px\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.widget_18)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_4)
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_3.addWidget(self.widget_12)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Meu Perfil"))
        self.label_4.setText(_translate("MainWindow", "\"Cargo\""))
        self.label_3.setText(_translate("MainWindow", "\"Nome\""))
        self.label_5.setText(_translate("MainWindow", "\"Setor:\""))
        self.pushButton.setText(_translate("MainWindow", "Editar Perfil"))
        self.label_6.setText(_translate("MainWindow", "Dados Pessoais"))
        self.label_7.setText(_translate("MainWindow", "Nome:"))
        self.label_8.setText(_translate("MainWindow", "Telefone:"))
        self.label_9.setText(_translate("MainWindow", "Endereçode E-mail:"))
        self.label_10.setText(_translate("MainWindow", "E-mail:"))
        self.label_11.setText(_translate("MainWindow", "Posição Funcional:"))
        self.label_12.setText(_translate("MainWindow", "Cargo:"))
        self.label_13.setText(_translate("MainWindow", "Setor:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
