# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\bag_item_cad.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(984, 690)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.frame_2)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 45))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header_frame.setStyleSheet("background-color: #057A3A")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.header_frame)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.return_btn = QtWidgets.QPushButton(self.header_frame)
        self.return_btn.setMinimumSize(QtCore.QSize(33, 33))
        self.return_btn.setMaximumSize(QtCore.QSize(66, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.return_btn.setFont(font)
        self.return_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.return_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 2px solid rgb(255, 255, 255);\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(0, 170, 0);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}\n"
"")
        self.return_btn.setObjectName("return_btn")
        self.horizontalLayout_5.addWidget(self.return_btn)
        self.verticalLayout.addWidget(self.header_frame)
        self.base_frame = QtWidgets.QFrame(self.frame_2)
        self.base_frame.setMinimumSize(QtCore.QSize(0, 150))
        self.base_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.base_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.base_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.base_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(280, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.chave_acesso = QtWidgets.QLineEdit(self.frame_6)
        self.chave_acesso.setMinimumSize(QtCore.QSize(0, 24))
        self.chave_acesso.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.chave_acesso.setFont(font)
        self.chave_acesso.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.chave_acesso.setAlignment(QtCore.Qt.AlignCenter)
        self.chave_acesso.setObjectName("chave_acesso")
        self.verticalLayout_10.addWidget(self.chave_acesso)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.rec_p = QtWidgets.QLineEdit(self.frame_6)
        self.rec_p.setMinimumSize(QtCore.QSize(0, 24))
        self.rec_p.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.rec_p.setFont(font)
        self.rec_p.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.rec_p.setAlignment(QtCore.Qt.AlignCenter)
        self.rec_p.setObjectName("rec_p")
        self.verticalLayout_10.addWidget(self.rec_p)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.base_frame)
        self.frame_7.setMinimumSize(QtCore.QSize(240, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.n_nota = QtWidgets.QLineEdit(self.frame_7)
        self.n_nota.setMinimumSize(QtCore.QSize(220, 24))
        self.n_nota.setMaximumSize(QtCore.QSize(220, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.n_nota.setFont(font)
        self.n_nota.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.n_nota.setAlignment(QtCore.Qt.AlignCenter)
        self.n_nota.setObjectName("n_nota")
        self.verticalLayout_9.addWidget(self.n_nota)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.n_serie = QtWidgets.QLineEdit(self.frame_7)
        self.n_serie.setMinimumSize(QtCore.QSize(220, 24))
        self.n_serie.setMaximumSize(QtCore.QSize(220, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.n_serie.setFont(font)
        self.n_serie.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"")
        self.n_serie.setAlignment(QtCore.Qt.AlignCenter)
        self.n_serie.setObjectName("n_serie")
        self.verticalLayout_9.addWidget(self.n_serie)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_13 = QtWidgets.QFrame(self.base_frame)
        self.frame_13.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.frame_18.setFont(font)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.date_buy = QtWidgets.QDateEdit(self.frame_18)
        self.date_buy.setMinimumSize(QtCore.QSize(90, 20))
        self.date_buy.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.date_buy.setFont(font)
        self.date_buy.setStyleSheet("QDateEdit{\n"
"color:rgb(0, 85, 0);\n"
"background-color:white;    \n"
"border-radius: 3px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"}\n"
"\n"
"\n"
"/* Estilo dos botões de navegação */\n"
"QCalendarWidget QToolButton {\n"
"    color: #FFFFFF; /* Cor do texto dos botões */\n"
"    background-color: rgb(0, 85, 0); /* Cor de fundo dos botões */\n"
"    border: none; /* Sem borda */\n"
"}\n"
"\n"
"")
        self.date_buy.setDisplayFormat("dd/MM/yyyy")
        self.date_buy.setCalendarPopup(True)
        self.date_buy.setTimeSpec(QtCore.Qt.TimeZone)
        self.date_buy.setObjectName("date_buy")
        self.verticalLayout_16.addWidget(self.date_buy)
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        self.label_12.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_16.addWidget(self.label_12)
        self.date_rec = QtWidgets.QDateEdit(self.frame_18)
        self.date_rec.setMinimumSize(QtCore.QSize(90, 20))
        self.date_rec.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.date_rec.setFont(font)
        self.date_rec.setStyleSheet("QDateEdit{\n"
"color:rgb(0, 85, 0);\n"
"background-color:white;    \n"
"border-radius: 3px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"}\n"
"\n"
"\n"
"/* Estilo dos botões de navegação */\n"
"QCalendarWidget QToolButton {\n"
"    color: #FFFFFF; /* Cor do texto dos botões */\n"
"    background-color: rgb(0, 85, 0); /* Cor de fundo dos botões */\n"
"    border: none; /* Sem borda */\n"
"}\n"
"\n"
"")
        self.date_rec.setCalendarPopup(True)
        self.date_rec.setObjectName("date_rec")
        self.verticalLayout_16.addWidget(self.date_rec)
        self.horizontalLayout_9.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_13)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.forn_name = QtWidgets.QComboBox(self.frame_19)
        self.forn_name.setMinimumSize(QtCore.QSize(150, 24))
        self.forn_name.setMaximumSize(QtCore.QSize(220, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.forn_name.setFont(font)
        self.forn_name.setStyleSheet("QComboBox{\n"
"background-color : rgb(255, 248, 248);\n"
"border:1px solid gray;\n"
"}\n"
"\n"
"\n"
"")
        self.forn_name.setObjectName("forn_name")
        self.verticalLayout_15.addWidget(self.forn_name)
        self.horizontalLayout_9.addWidget(self.frame_19, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.verticalLayout.addWidget(self.base_frame)
        self.prod_frame = QtWidgets.QFrame(self.frame_2)
        self.prod_frame.setMinimumSize(QtCore.QSize(810, 161))
        self.prod_frame.setMaximumSize(QtCore.QSize(1200, 161))
        self.prod_frame.setStyleSheet("background-color: #057A3A;\n"
"border-radius: 15px;\n"
"")
        self.prod_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prod_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prod_frame.setObjectName("prod_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.prod_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.prod_frame)
        self.frame_4.setMinimumSize(QtCore.QSize(450, 150))
        self.frame_4.setMaximumSize(QtCore.QSize(360, 110))
        self.frame_4.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setMinimumSize(QtCore.QSize(420, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(420, 16777215))
        self.frame_14.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_18.addWidget(self.label_8)
        self.name_prod = QtWidgets.QLineEdit(self.frame_14)
        self.name_prod.setMinimumSize(QtCore.QSize(0, 24))
        self.name_prod.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.name_prod.setFont(font)
        self.name_prod.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.name_prod.setAlignment(QtCore.Qt.AlignCenter)
        self.name_prod.setObjectName("name_prod")
        self.verticalLayout_18.addWidget(self.name_prod)
        self.frame_12 = QtWidgets.QFrame(self.frame_14)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 66))
        self.frame_12.setStyleSheet("background-color:transparent;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_17 = QtWidgets.QFrame(self.frame_12)
        self.frame_17.setStyleSheet("background-color:transparent;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.c_sit = QtWidgets.QComboBox(self.frame_17)
        self.c_sit.setMinimumSize(QtCore.QSize(0, 21))
        self.c_sit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.c_sit.setFont(font)
        self.c_sit.setStyleSheet("QComboBox{\n"
"background-color : rgb(255, 248, 248);\n"
"border:1px solid gray;\n"
"}\n"
"\n"
"\n"
"")
        self.c_sit.setObjectName("c_sit")
        self.verticalLayout_14.addWidget(self.c_sit)
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        self.frame_16.setStyleSheet("background-color:transparent;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.c_setor = QtWidgets.QComboBox(self.frame_16)
        self.c_setor.setMinimumSize(QtCore.QSize(0, 21))
        self.c_setor.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.c_setor.setFont(font)
        self.c_setor.setStyleSheet("QComboBox{\n"
"background-color : rgb(255, 248, 248);\n"
"border:1px solid gray;\n"
"}\n"
"\n"
"\n"
"")
        self.c_setor.setObjectName("c_setor")
        self.verticalLayout_13.addWidget(self.c_setor)
        self.horizontalLayout_8.addWidget(self.frame_16)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setStyleSheet("background-color:transparent;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.cat_item = QtWidgets.QComboBox(self.frame_15)
        self.cat_item.setMinimumSize(QtCore.QSize(0, 21))
        self.cat_item.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.cat_item.setFont(font)
        self.cat_item.setStyleSheet("QComboBox{\n"
"background-color : rgb(255, 248, 248);\n"
"border:1px solid gray;\n"
"}\n"
"\n"
"\n"
"")
        self.cat_item.setObjectName("cat_item")
        self.verticalLayout_5.addWidget(self.cat_item)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.verticalLayout_18.addWidget(self.frame_12)
        self.verticalLayout_17.addWidget(self.frame_14)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.prod_frame)
        self.frame_5.setMinimumSize(QtCore.QSize(360, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(360, 150))
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setMinimumSize(QtCore.QSize(120, 120))
        self.frame_11.setMaximumSize(QtCore.QSize(200, 120))
        self.frame_11.setStyleSheet("border:none;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.value_prod = QtWidgets.QLineEdit(self.frame_11)
        self.value_prod.setMinimumSize(QtCore.QSize(0, 24))
        self.value_prod.setMaximumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.value_prod.setFont(font)
        self.value_prod.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.value_prod.setAlignment(QtCore.Qt.AlignCenter)
        self.value_prod.setObjectName("value_prod")
        self.verticalLayout_6.addWidget(self.value_prod, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.qnt = QtWidgets.QSpinBox(self.frame_11)
        self.qnt.setMinimumSize(QtCore.QSize(60, 24))
        self.qnt.setMaximumSize(QtCore.QSize(72, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.qnt.setFont(font)
        self.qnt.setStyleSheet("background-color:white;    \n"
"border:1px solid green;\n"
"")
        self.qnt.setAlignment(QtCore.Qt.AlignCenter)
        self.qnt.setMinimum(1)
        self.qnt.setMaximum(9999)
        self.qnt.setObjectName("qnt")
        self.verticalLayout_6.addWidget(self.qnt, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.frame_valor = QtWidgets.QFrame(self.frame_5)
        self.frame_valor.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frame_valor.setStyleSheet("border:none;")
        self.frame_valor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_valor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_valor.setObjectName("frame_valor")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_valor)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.value_r = QtWidgets.QLabel(self.frame_valor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.value_r.setFont(font)
        self.value_r.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.value_r.setObjectName("value_r")
        self.verticalLayout_7.addWidget(self.value_r, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.frame_valor)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.prod_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(120, 120))
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ok_btn = QtWidgets.QPushButton(self.frame_3)
        self.ok_btn.setMinimumSize(QtCore.QSize(45, 36))
        self.ok_btn.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ok_btn.setFont(font)
        self.ok_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_btn.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout_8.addWidget(self.ok_btn)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.prod_frame)
        self.add_frame = QtWidgets.QFrame(self.frame_2)
        self.add_frame.setMinimumSize(QtCore.QSize(0, 180))
        self.add_frame.setMaximumSize(QtCore.QSize(16777215, 180))
        self.add_frame.setStyleSheet("margin-top:3px;")
        self.add_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_frame.setObjectName("add_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.add_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.list_itens_add = QtWidgets.QTableView(self.add_frame)
        self.list_itens_add.setMinimumSize(QtCore.QSize(0, 112))
        self.list_itens_add.setMaximumSize(QtCore.QSize(16777215, 240))
        self.list_itens_add.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"\n"
"")
        self.list_itens_add.setObjectName("list_itens_add")
        self.horizontalLayout_4.addWidget(self.list_itens_add)
        self.del = QtWidgets.QPushButton(self.add_frame)
        self.del.setMinimumSize(QtCore.QSize(45, 45))
        self.del.setMaximumSize(QtCore.QSize(45, 45))
        self.del.setStyleSheet("QPushButton { \n"
"    background-color: rgb(170, 0, 0);\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    padding:5px\n"
" }\n"
"\n"
"QPushButton:hover{;color:white;\n"
"background-color:rgb(255, 0, 4)}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color:rgb(231, 0, 0)\n"
" }")
        self.del.setObjectName("del")
        self.horizontalLayout_4.addWidget(self.del, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.add_frame)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 72))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 72))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_9)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cancelBtn = QtWidgets.QPushButton(self.frame_8)
        self.cancelBtn.setMinimumSize(QtCore.QSize(90, 36))
        self.cancelBtn.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout_4.addWidget(self.cancelBtn, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_6.addWidget(self.frame_8, 0, QtCore.Qt.AlignLeft)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cadItens = QtWidgets.QPushButton(self.frame_10)
        self.cadItens.setMinimumSize(QtCore.QSize(90, 36))
        self.cadItens.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.cadItens.setFont(font)
        self.cadItens.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cadItens.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.cadItens.setObjectName("cadItens")
        self.verticalLayout_3.addWidget(self.cadItens)
        self.horizontalLayout_6.addWidget(self.frame_10, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_12.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.return_btn.setText(_translate("Form", "Voltar"))
        self.label_7.setText(_translate("Form", "Chave de Acesso"))
        self.label_6.setText(_translate("Form", "Recebido por"))
        self.label_5.setText(_translate("Form", "Número"))
        self.label_4.setText(_translate("Form", "Série"))
        self.label_3.setText(_translate("Form", "Data de Aquisição"))
        self.label_12.setText(_translate("Form", "Data de Recebimento"))
        self.date_rec.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.label_13.setText(_translate("Form", "Fornecedor"))
        self.label_8.setText(_translate("Form", "Nome do Produto"))
        self.label_15.setText(_translate("Form", "Situação"))
        self.label_14.setText(_translate("Form", "Setor Responsável"))
        self.label_9.setText(_translate("Form", "Categoria"))
        self.label_10.setText(_translate("Form", "Valor Unitário"))
        self.label_11.setText(_translate("Form", "Quantidade"))
        self.value_r.setText(_translate("Form", "Valor Total:"))
        self.ok_btn.setText(_translate("Form", "OK"))
        self.del.setText(_translate("Form", "X"))
        self.cancelBtn.setText(_translate("Form", "LIMPAR"))
        self.cadItens.setText(_translate("Form", "CONFIRMAR"))
