# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Documents\GitHub\controle_patrimonio\PATP\bckp\asset_ctrl\templates\interfaces\bag.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 737)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_edit_2 = QtWidgets.QFrame(Form)
        self.frame_edit_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edit_2.setObjectName("frame_edit_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_edit_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout.addWidget(self.frame_edit_2)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cad_frame = QtWidgets.QFrame(self.frame_2)
        self.cad_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cad_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cad_frame.setObjectName("cad_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cad_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.f_text = QtWidgets.QTextBrowser(self.cad_frame)
        self.f_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.f_text.setStyleSheet("background-color:transparent;")
        self.f_text.setObjectName("f_text")
        self.verticalLayout_6.addWidget(self.f_text)
        self.verticalLayout_9.addWidget(self.cad_frame)
        self.frame_menu = QtWidgets.QFrame(self.frame_2)
        self.frame_menu.setMinimumSize(QtCore.QSize(0, 54))
        self.frame_menu.setMaximumSize(QtCore.QSize(16777215, 54))
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.item_btn = QtWidgets.QPushButton(self.frame_menu)
        self.item_btn.setMinimumSize(QtCore.QSize(90, 45))
        self.item_btn.setMaximumSize(QtCore.QSize(90, 45))
        self.item_btn.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.item_btn.setObjectName("item_btn")
        self.horizontalLayout_4.addWidget(self.item_btn)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 45))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 45))
        self.pushButton_3.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 45))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 45))
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.frame_menu, 0, QtCore.Qt.AlignVCenter)
        self.body_frame = QtWidgets.QFrame(self.frame_2)
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.central_frame = QtWidgets.QFrame(self.body_frame)
        self.central_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.central_frame.setMaximumSize(QtCore.QSize(16777215, 810))
        self.central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_frame.setObjectName("central_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_search = QtWidgets.QFrame(self.central_frame)
        self.frame_search.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_search.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_search.setStyleSheet("border-radius:5px;\n"
"border:5px solid #057A3A;\n"
"background-color: #057A3A;\n"
"")
        self.frame_search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search.setObjectName("frame_search")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_search)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.regItem = QtWidgets.QPushButton(self.frame_search)
        self.regItem.setMinimumSize(QtCore.QSize(90, 36))
        self.regItem.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.regItem.setFont(font)
        self.regItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.regItem.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0);\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.regItem.setObjectName("regItem")
        self.horizontalLayout_3.addWidget(self.regItem, 0, QtCore.Qt.AlignTop)
        self.line_search = QtWidgets.QLineEdit(self.frame_search)
        self.line_search.setMinimumSize(QtCore.QSize(90, 33))
        self.line_search.setMaximumSize(QtCore.QSize(400, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line_search.setFont(font)
        self.line_search.setStyleSheet("QLineEdit{\n"
"background-color:white;    ;\n"
"border-radius: 10px;\n"
"color:black;\n"
"border:none;\n"
"}\n"
"")
        self.line_search.setAlignment(QtCore.Qt.AlignCenter)
        self.line_search.setObjectName("line_search")
        self.horizontalLayout_3.addWidget(self.line_search)
        self.verticalLayout_2.addWidget(self.frame_search, 0, QtCore.Qt.AlignVCenter)
        self.frame_view = QtWidgets.QFrame(self.central_frame)
        self.frame_view.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_view)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_bag = QtWidgets.QTableView(self.frame_view)
        self.table_bag.setMinimumSize(QtCore.QSize(690, 360))
        self.table_bag.setMaximumSize(QtCore.QSize(16777215, 620))
        self.table_bag.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.table_bag.setShowGrid(True)
        self.table_bag.setGridStyle(QtCore.Qt.SolidLine)
        self.table_bag.setObjectName("table_bag")
        self.horizontalLayout_2.addWidget(self.table_bag, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_view, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.central_frame)
        self.lateral_frame = QtWidgets.QFrame(self.body_frame)
        self.lateral_frame.setMinimumSize(QtCore.QSize(150, 0))
        self.lateral_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lateral_frame.setStyleSheet("border-radius:10px;\n"
"background-color: #057A3A;")
        self.lateral_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lateral_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lateral_frame.setObjectName("lateral_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lateral_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_top_frame = QtWidgets.QFrame(self.lateral_frame)
        self.btn_top_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_top_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_top_frame.setObjectName("btn_top_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btn_top_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_edit = QtWidgets.QFrame(self.btn_top_frame)
        self.frame_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_edit.setStyleSheet("background-color:transparent;")
        self.frame_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edit.setObjectName("frame_edit")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_edit)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.edit_btn = QtWidgets.QPushButton(self.frame_edit)
        self.edit_btn.setMinimumSize(QtCore.QSize(90, 36))
        self.edit_btn.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.edit_btn.setFont(font)
        self.edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout_7.addWidget(self.edit_btn)
        self.verticalLayout_4.addWidget(self.frame_edit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_detail = QtWidgets.QFrame(self.btn_top_frame)
        self.frame_detail.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_detail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_detail.setStyleSheet("background-color:transparent;\n"
"border-bottom:none")
        self.frame_detail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_detail.setObjectName("frame_detail")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_detail)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.details_btn = QtWidgets.QPushButton(self.frame_detail)
        self.details_btn.setMinimumSize(QtCore.QSize(90, 36))
        self.details_btn.setMaximumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.details_btn.setFont(font)
        self.details_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.details_btn.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.details_btn.setObjectName("details_btn")
        self.verticalLayout_8.addWidget(self.details_btn)
        self.verticalLayout_4.addWidget(self.frame_detail, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.btn_top_frame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.lateral_frame)
        self.verticalLayout_9.addWidget(self.body_frame)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.f_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#004c00;\">Gerenciamento de Itens:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#004c00;\">Esta tela permite realizar as principais ações para gerenciar itens de forma prática e direta, nela são exibidos os itens com as principais informações organizadas, sendo possível selecionar e interagir com os dados diretamente. Algumas funções podem ser restritas a cargos específicos para maior controle.</span></p></body></html>"))
        self.item_btn.setText(_translate("Form", "prod_btn"))
        self.pushButton_3.setText(_translate("Form", "local_btn"))
        self.pushButton.setText(_translate("Form", "ptr_btn"))
        self.regItem.setText(_translate("Form", "Registrar"))
        self.line_search.setPlaceholderText(_translate("Form", "Pesquisar"))
        self.edit_btn.setText(_translate("Form", "Editar"))
        self.details_btn.setText(_translate("Form", "Detalhes"))
