# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\cargo_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(963, 378)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 360))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 360))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_7)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_6.setStyleSheet("border-radius:10px;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setStyleSheet("border:0;\n"
"background-color:transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("border:0;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 33))
        self.lineEdit.setMaximumSize(QtCore.QSize(240, 24))
        self.lineEdit.setStyleSheet("background-color:white;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.verticalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter)
        self.box_cargo = QtWidgets.QComboBox(self.frame_10)
        self.box_cargo.setMinimumSize(QtCore.QSize(240, 24))
        self.box_cargo.setMaximumSize(QtCore.QSize(240, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.box_cargo.setFont(font)
        self.box_cargo.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.box_cargo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_cargo.setStyleSheet("\n"
"\n"
"\n"
"QComboBox{background-color:white;\n"
"border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 25px; /* Largura do quadrado */\n"
"align-itens:center;\n"
"}\n"
"\n"
" ")
        self.box_cargo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.box_cargo.setObjectName("box_cargo")
        self.box_cargo.addItem("")
        self.verticalLayout_7.addWidget(self.box_cargo, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setStyleSheet("border:0;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_5.setMinimumSize(QtCore.QSize(71, 33))
        self.pushButton_5.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_5.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_6.setMinimumSize(QtCore.QSize(71, 33))
        self.pushButton_6.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_6.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_7.setMinimumSize(QtCore.QSize(71, 33))
        self.pushButton_7.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_7.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.frame_9)
        self.frame_3.setMinimumSize(QtCore.QSize(90, 90))
        self.frame_3.setMaximumSize(QtCore.QSize(90, 90))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_9)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_8.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setMaximumSize(QtCore.QSize(70, 33))
        self.pushButton_9.setStyleSheet("\n"
"\n"
"QPushButton { color: rgb(243, 239, 238);\n"
"    border-radius:15px;        \n"
"    border: 4px solid #00BF63;\n"
"    background-color:#00BF63;\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(255, 240, 238);color:#00BF63}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
"    background-color: rgb(227, 227, 227);\n"
" \n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout_9.addWidget(self.frame)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_cargo.setItemText(0, _translate("Form", "cargo"))
        self.pushButton_5.setText(_translate("Form", "Cofirmar"))
        self.pushButton_6.setText(_translate("Form", "Cancelar"))
        self.pushButton_7.setText(_translate("Form", "+"))
        self.label.setText(_translate("Form", "Usuários com o cargo ____ : "))
        self.label_2.setText(_translate("Form", "Quantidade de cargos cadastrados:"))
        self.label_3.setText(_translate("Form", "Última modificação:"))
        self.checkBox_5.setText(_translate("Form", "Acesso Geral"))
        self.checkBox.setText(_translate("Form", "Permissão de Registro"))
        self.checkBox_2.setText(_translate("Form", "Controle Administrativo"))
        self.checkBox_3.setText(_translate("Form", "Controle de Usuários"))
        self.checkBox_4.setText(_translate("Form", "Permissão de Modificação"))
        self.checkBox_6.setText(_translate("Form", "Permissão de Visualização"))
        self.pushButton.setText(_translate("Form", "Editar"))
        self.pushButton_8.setText(_translate("Form", "Confirmar"))
        self.pushButton_9.setText(_translate("Form", "Cancelar"))
