# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\cargo_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(963, 378)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 360))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 360))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_7)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setStyleSheet("border-radius:10px;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_6.setStyleSheet("border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setStyleSheet("border:0;\n"
"background-color:transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setStyleSheet("border:0;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.new_cargo = QtWidgets.QLineEdit(self.frame_11)
        self.new_cargo.setMinimumSize(QtCore.QSize(240, 24))
        self.new_cargo.setMaximumSize(QtCore.QSize(240, 24))
        self.new_cargo.setStyleSheet("background-color:white;\n"
"border-radius:6px")
        self.new_cargo.setObjectName("new_cargo")
        self.verticalLayout_8.addWidget(self.new_cargo)
        self.verticalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter)
        self.box_cargo = QtWidgets.QComboBox(self.frame_10)
        self.box_cargo.setMinimumSize(QtCore.QSize(240, 24))
        self.box_cargo.setMaximumSize(QtCore.QSize(240, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.box_cargo.setFont(font)
        self.box_cargo.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.box_cargo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_cargo.setStyleSheet("\n"
"\n"
"\n"
"QComboBox{background-color:white;\n"
"border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 25px; /* Largura do quadrado */\n"
"align-itens:center;\n"
"}\n"
"\n"
" ")
        self.box_cargo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.box_cargo.setObjectName("box_cargo")
        self.verticalLayout_7.addWidget(self.box_cargo, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setStyleSheet("border:0;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_confirm = QtWidgets.QPushButton(self.frame_12)
        self.btn_confirm.setMinimumSize(QtCore.QSize(71, 33))
        self.btn_confirm.setMaximumSize(QtCore.QSize(70, 40))
        self.btn_confirm.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btn_confirm.setObjectName("btn_confirm")
        self.verticalLayout_6.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.frame_12)
        self.btn_cancel.setMinimumSize(QtCore.QSize(71, 33))
        self.btn_cancel.setMaximumSize(QtCore.QSize(70, 40))
        self.btn_cancel.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.verticalLayout_6.addWidget(self.btn_cancel)
        self.add_cargo = QtWidgets.QPushButton(self.frame_12)
        self.add_cargo.setMinimumSize(QtCore.QSize(71, 33))
        self.add_cargo.setMaximumSize(QtCore.QSize(70, 33))
        self.add_cargo.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.add_cargo.setObjectName("add_cargo")
        self.verticalLayout_6.addWidget(self.add_cargo)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setStyleSheet("border:none;\n"
"color:white;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setStyleSheet("border:none;\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setStyleSheet("border:none;\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.acesso_geral = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.acesso_geral.setFont(font)
        self.acesso_geral.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.acesso_geral.setObjectName("acesso_geral")
        self.verticalLayout_2.addWidget(self.acesso_geral)
        self.pode_registrar = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pode_registrar.setFont(font)
        self.pode_registrar.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.pode_registrar.setObjectName("pode_registrar")
        self.verticalLayout_2.addWidget(self.pode_registrar)
        self.controle_adm = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.controle_adm.setFont(font)
        self.controle_adm.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.controle_adm.setObjectName("controle_adm")
        self.verticalLayout_2.addWidget(self.controle_adm)
        self.controle_usuario = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.controle_usuario.setFont(font)
        self.controle_usuario.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.controle_usuario.setObjectName("controle_usuario")
        self.verticalLayout_2.addWidget(self.controle_usuario)
        self.pode_modificar = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pode_modificar.setFont(font)
        self.pode_modificar.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.pode_modificar.setObjectName("pode_modificar")
        self.verticalLayout_2.addWidget(self.pode_modificar)
        self.pode_visualizar = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pode_visualizar.setFont(font)
        self.pode_visualizar.setStyleSheet(" QCheckBox {\n"
"    spacing: 5px; /* Espaçamento entre o checkbox e o texto */\n"
"    color: rgb(0, 85, 0); /* Cor do texto */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;  /* Largura do checkbox */\n"
"    height: 20px; /* Altura do checkbox */\n"
"      background-color: #aaaaaa; /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(74, 74, 74);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"    border: 2px solid rgb(0, 85, 0);\n"
"    background-color: #4CAF50; /* Cor de fundo quando está marcado */\n"
"    border: 2px solid #4CAF50;\n"
" \n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"      background-color: rgb(97, 166, 99); /* Cor de fundo padrão */\n"
"border: 2px solid rgb(0, 85, 0); \n"
"}")
        self.pode_visualizar.setObjectName("pode_visualizar")
        self.verticalLayout_2.addWidget(self.pode_visualizar)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.frame_9)
        self.frame_3.setMinimumSize(QtCore.QSize(90, 90))
        self.frame_3.setMaximumSize(QtCore.QSize(90, 90))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.edit_cargo = QtWidgets.QPushButton(self.frame_3)
        self.edit_cargo.setMaximumSize(QtCore.QSize(70, 33))
        self.edit_cargo.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.edit_cargo.setObjectName("edit_cargo")
        self.verticalLayout_10.addWidget(self.edit_cargo)
        self.verticalLayout_9.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_9)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_confirm_edit = QtWidgets.QPushButton(self.frame)
        self.btn_confirm_edit.setMaximumSize(QtCore.QSize(70, 33))
        self.btn_confirm_edit.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btn_confirm_edit.setObjectName("btn_confirm_edit")
        self.verticalLayout_5.addWidget(self.btn_confirm_edit)
        self.btn_edit_cancel = QtWidgets.QPushButton(self.frame)
        self.btn_edit_cancel.setMaximumSize(QtCore.QSize(70, 33))
        self.btn_edit_cancel.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btn_edit_cancel.setObjectName("btn_edit_cancel")
        self.verticalLayout_5.addWidget(self.btn_edit_cancel)
        self.verticalLayout_9.addWidget(self.frame)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_confirm.setText(_translate("Form", "Cofirmar"))
        self.btn_cancel.setText(_translate("Form", "Cancelar"))
        self.add_cargo.setText(_translate("Form", "+"))
        self.label.setText(_translate("Form", "Usuários com o cargo ____ : "))
        self.label_2.setText(_translate("Form", "Quantidade de cargos cadastrados:"))
        self.label_3.setText(_translate("Form", "Última modificação:"))
        self.acesso_geral.setText(_translate("Form", "Acesso Geral"))
        self.pode_registrar.setText(_translate("Form", "Permissão de Registro"))
        self.controle_adm.setText(_translate("Form", "Controle Administrativo"))
        self.controle_usuario.setText(_translate("Form", "Controle de Usuários"))
        self.pode_modificar.setText(_translate("Form", "Permissão de Modificação"))
        self.pode_visualizar.setText(_translate("Form", "Permissão de Visualização"))
        self.edit_cargo.setText(_translate("Form", "Editar"))
        self.btn_confirm_edit.setText(_translate("Form", "Confirmar"))
        self.btn_edit_cancel.setText(_translate("Form", "Cancelar"))
