# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\config_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(919, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setStyleSheet("border-radius:15px;\n"
"border:5px solid #057A3A;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cargo_config = QtWidgets.QPushButton(self.frame_3)
        self.cargo_config.setMinimumSize(QtCore.QSize(90, 36))
        self.cargo_config.setMaximumSize(QtCore.QSize(150, 50))
        self.cargo_config.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.cargo_config.setObjectName("cargo_config")
        self.horizontalLayout.addWidget(self.cargo_config)
        self.cat_config = QtWidgets.QPushButton(self.frame_3)
        self.cat_config.setMinimumSize(QtCore.QSize(90, 36))
        self.cat_config.setMaximumSize(QtCore.QSize(150, 50))
        self.cat_config.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.cat_config.setObjectName("cat_config")
        self.horizontalLayout.addWidget(self.cat_config)
        self.local_config = QtWidgets.QPushButton(self.frame_3)
        self.local_config.setMinimumSize(QtCore.QSize(90, 36))
        self.local_config.setMaximumSize(QtCore.QSize(150, 50))
        self.local_config.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.local_config.setObjectName("local_config")
        self.horizontalLayout.addWidget(self.local_config)
        self.fornec_config = QtWidgets.QPushButton(self.frame_3)
        self.fornec_config.setMinimumSize(QtCore.QSize(90, 36))
        self.fornec_config.setMaximumSize(QtCore.QSize(150, 50))
        self.fornec_config.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.fornec_config.setObjectName("fornec_config")
        self.horizontalLayout.addWidget(self.fornec_config)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.intro_frame = QtWidgets.QFrame(self.frame)
        self.intro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.intro_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.intro_frame.setObjectName("intro_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.intro_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.intro_frame)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 600))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color:white;\n"
"border-radius:15px;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.intro_frame)
        self.configs_frame = QtWidgets.QFrame(self.frame)
        self.configs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configs_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configs_frame.setObjectName("configs_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.configs_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5.addWidget(self.configs_frame)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cargo_config.setText(_translate("Form", "Cargos"))
        self.cat_config.setText(_translate("Form", "Categorias"))
        self.local_config.setText(_translate("Form", "Locais"))
        self.fornec_config.setText(_translate("Form", "Fornecedores"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\"> Lorem ipsum dolor sit amet. Qui praesentium eaque ut culpa rerum et laborum cupiditate ut sint illum eos fuga exercitationem et veritatis quasi. Qui illo quasi est inventore rerum est exercitationem earum et assumenda error eos explicabo consequatur sed quod earum! Ad ipsam dolor et commodi quos qui quas ipsam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Qui inventore fugit rem officiis animi in totam natus a perspiciatis consequatur ex assumenda accusantium. Qui corrupti voluptatem id sunt deleniti hic aperiam odio quo beatae nobis! Ut atque similique eos illo excepturi est dolorem exercitationem est sint molestiae est animi numquam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Sit quia explicabo aut earum doloribus a maxime beatae ut maxime labore aut commodi sint. Id ipsam asperiores quo corrupti suscipit ea voluptatem distinctio?  Lorem ipsum dolor sit amet. Qui praesentium eaque ut culpa rerum et laborum cupiditate ut sint illum eos fuga exercitationem et veritatis quasi. Qui illo quasi est inventore rerum est exercitationem earum et assumenda error eos explicabo consequatur sed quod earum! Ad ipsam dolor et commodi quos qui quas ipsam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Qui inventore fugit rem officiis animi in totam natus a perspiciatis consequatur ex assumenda accusantium. Qui corrupti voluptatem id sunt deleniti hic aperiam odio quo beatae nobis! Ut atque similique eos illo excepturi est dolorem exercitationem est sint molestiae est animi numquam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Sit quia explicabo aut earum doloribus a maxime beatae ut maxime labore aut commodi sint. Id ipsam asperiores quo corrupti suscipit ea voluptatem distinctio?  Lorem ipsum dolor sit amet. Qui praesentium eaque ut culpa rerum et laborum cupiditate ut sint illum eos fuga exercitationem et veritatis quasi. Qui illo quasi est inventore rerum est exercitationem earum et assumenda error eos explicabo consequatur sed quod earum! Ad ipsam dolor et commodi quos qui quas ipsam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Qui inventore fugit rem officiis animi in totam natus a perspiciatis consequatur ex assumenda accusantium. Qui corrupti voluptatem id sunt deleniti hic aperiam odio quo beatae nobis! Ut atque similique eos illo excepturi est dolorem exercitationem est sint molestiae est animi numquam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Sit quia explicabo aut earum doloribus a maxime beatae ut maxime labore aut commodi sint. Id ipsam asperiores quo corrupti suscipit ea voluptatem distinctio?  Lorem ipsum dolor sit amet. Qui praesentium eaque ut culpa rerum et laborum cupiditate ut sint illum eos fuga exercitationem et veritatis quasi. Qui illo quasi est inventore rerum est exercitationem earum et assumenda error eos explicabo consequatur sed quod earum! Ad ipsam dolor et commodi quos qui quas ipsam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Qui inventore fugit rem officiis animi in totam natus a perspiciatis consequatur ex assumenda accusantium. Qui corrupti voluptatem id sunt deleniti hic aperiam odio quo beatae nobis! Ut atque similique eos illo excepturi est dolorem exercitationem est sint molestiae est animi numquam. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#005f13;\">Sit quia explicabo aut earum doloribus a maxime beatae ut maxime labore aut commodi sint. Id ipsam asperiores quo corrupti suscipit ea voluptatem distinctio? </span></p></body></html>"))
