# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Documents\GitHub\controle_patrimonio\PATP\bckp\asset_ctrl\templates\interfaces\local_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(939, 378)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 360))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 360))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_7)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_6.setStyleSheet("border-radius:10px;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setStyleSheet("border:0;\n"
"background-color:transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.box_local = QtWidgets.QComboBox(self.frame_10)
        self.box_local.setMinimumSize(QtCore.QSize(240, 24))
        self.box_local.setMaximumSize(QtCore.QSize(240, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.box_local.setFont(font)
        self.box_local.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.box_local.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_local.setStyleSheet("\n"
"\n"
"\n"
"QComboBox{background-color:white;\n"
"border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 25px; /* Largura do quadrado */\n"
"align-itens:center;\n"
"}\n"
"\n"
" ")
        self.box_local.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.box_local.setObjectName("box_local")
        self.box_local.addItem("")
        self.verticalLayout_7.addWidget(self.box_local, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_10, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setStyleSheet("border:0;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.add_btn = QtWidgets.QPushButton(self.frame_12)
        self.add_btn.setMinimumSize(QtCore.QSize(71, 33))
        self.add_btn.setMaximumSize(QtCore.QSize(70, 33))
        self.add_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_6.addWidget(self.add_btn)
        self.horizontalLayout_2.addWidget(self.frame_12, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.frame_6, 0, QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("color: rgb(0, 85, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("color: rgb(0, 85, 0);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.local_line = QtWidgets.QLineEdit(self.frame_4)
        self.local_line.setMinimumSize(QtCore.QSize(240, 24))
        self.local_line.setMaximumSize(QtCore.QSize(240, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.local_line.setFont(font)
        self.local_line.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.local_line.setAlignment(QtCore.Qt.AlignCenter)
        self.local_line.setObjectName("local_line")
        self.verticalLayout_2.addWidget(self.local_line)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.lbl_qntd = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.lbl_qntd.setFont(font)
        self.lbl_qntd.setStyleSheet("color: rgb(0, 85, 0);")
        self.lbl_qntd.setObjectName("lbl_qntd")
        self.verticalLayout_5.addWidget(self.lbl_qntd, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(90, 90))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.confirm_btn = QtWidgets.QPushButton(self.frame_9)
        self.confirm_btn.setMinimumSize(QtCore.QSize(71, 33))
        self.confirm_btn.setMaximumSize(QtCore.QSize(71, 33))
        self.confirm_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.confirm_btn.setObjectName("confirm_btn")
        self.verticalLayout_9.addWidget(self.confirm_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.frame_9)
        self.cancel_btn.setMinimumSize(QtCore.QSize(71, 33))
        self.cancel_btn.setMaximumSize(QtCore.QSize(71, 33))
        self.cancel_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.verticalLayout_9.addWidget(self.cancel_btn)
        self.del_btn = QtWidgets.QPushButton(self.frame_9)
        self.del_btn.setMinimumSize(QtCore.QSize(71, 33))
        self.del_btn.setMaximumSize(QtCore.QSize(71, 33))
        self.del_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout_9.addWidget(self.del_btn)
        self.edit_btn = QtWidgets.QPushButton(self.frame_9)
        self.edit_btn.setMinimumSize(QtCore.QSize(71, 33))
        self.edit_btn.setMaximumSize(QtCore.QSize(71, 33))
        self.edit_btn.setStyleSheet("QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout_9.addWidget(self.edit_btn)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_local.setItemText(0, _translate("Form", "Locais"))
        self.add_btn.setText(_translate("Form", "+"))
        self.label_4.setText(_translate("Form", "Quantidades de itens neste local"))
        self.label_5.setText(_translate("Form", "Nome do local:"))
        self.lbl_qntd.setText(_translate("Form", "Quantidade de locais cadastrados:"))
        self.confirm_btn.setText(_translate("Form", "Confirmar"))
        self.cancel_btn.setText(_translate("Form", "Cancelar"))
        self.del_btn.setText(_translate("Form", "Deletar"))
        self.edit_btn.setText(_translate("Form", "Editar"))
