# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\local_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 703)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("border-radius:5px;\n"
"border:5px solid #057A3A;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("border:0;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_2.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_2.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_3.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_4.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_4.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("border:0;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_2 = QtWidgets.QListView(self.frame_9)
        self.listView_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.listView_2.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_4.addWidget(self.listView_2)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #057A3A;\n"
"color: rgb(255, 255, 255);\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.listView = QtWidgets.QListView(self.frame_8)
        self.listView.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.listView.setObjectName("listView")
        self.verticalLayout_5.addWidget(self.listView)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setMinimumSize(QtCore.QSize(300, 540))
        self.frame_10.setMaximumSize(QtCore.QSize(300, 400))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView_3 = QtWidgets.QListView(self.frame_10)
        self.listView_3.setMinimumSize(QtCore.QSize(150, 360))
        self.listView_3.setMaximumSize(QtCore.QSize(300, 360))
        self.listView_3.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_3.addWidget(self.listView_3)
        self.listView_4 = QtWidgets.QListView(self.frame_10)
        self.listView_4.setMinimumSize(QtCore.QSize(150, 0))
        self.listView_4.setMaximumSize(QtCore.QSize(300, 150))
        self.listView_4.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.listView_4.setObjectName("listView_4")
        self.verticalLayout_3.addWidget(self.listView_4)
        self.verticalLayout_7.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "bag"))
        self.pushButton_3.setText(_translate("Form", "patrimonio"))
        self.pushButton_4.setText(_translate("Form", "cad_local"))
        self.pushButton.setText(_translate("Form", "back"))
        self.label.setText(_translate("Form", "Produtos sem local:"))
