# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Desktop\PATP\asset_ctrl\templates\interfaces\rel_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 651)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("border-radius:\n"
"10px;\n"
"border:5px solid #057A3A;\n"
"background-color: #057A3A;\n"
"border-bottom: 2px solid rgb(108, 108, 108);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_2.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.cat_item_btn = QtWidgets.QPushButton(self.frame)
        self.cat_item_btn.setMinimumSize(QtCore.QSize(90, 36))
        self.cat_item_btn.setMaximumSize(QtCore.QSize(90, 36))
        self.cat_item_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cat_item_btn.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.cat_item_btn.setObjectName("cat_item_btn")
        self.horizontalLayout.addWidget(self.cat_item_btn)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("border:0")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_4.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_4.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.date_i = QtWidgets.QDateEdit(self.frame_7)
        self.date_i.setStyleSheet("QDateEdit{\n"
"color:rgb(0, 85, 0);\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"}\n"
"\n"
"\n"
"/* Estilo dos botões de navegação */\n"
"QCalendarWidget QToolButton {\n"
"    color: #FFFFFF; /* Cor do texto dos botões */\n"
"    background-color: rgb(0, 85, 0); /* Cor de fundo dos botões */\n"
"    border: none; /* Sem borda */\n"
"}")
        self.date_i.setAlignment(QtCore.Qt.AlignCenter)
        self.date_i.setCalendarPopup(True)
        self.date_i.setObjectName("date_i")
        self.horizontalLayout_4.addWidget(self.date_i)
        self.label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 76, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.date_f = QtWidgets.QDateEdit(self.frame_7)
        self.date_f.setStyleSheet("QDateEdit{\n"
"color:rgb(0, 85, 0);\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"}\n"
"\n"
"\n"
"/* Estilo dos botões de navegação */\n"
"QCalendarWidget QToolButton {\n"
"    color: #FFFFFF; /* Cor do texto dos botões */\n"
"    background-color: rgb(0, 85, 0); /* Cor de fundo dos botões */\n"
"    border: none; /* Sem borda */\n"
"}")
        self.date_f.setAlignment(QtCore.Qt.AlignCenter)
        self.date_f.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.date_f.setCalendarPopup(True)
        self.date_f.setObjectName("date_f")
        self.horizontalLayout_4.addWidget(self.date_f)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.listView = QtWidgets.QListView(self.frame_5)
        self.listView.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(90, 36))
        self.pushButton_5.setMaximumSize(QtCore.QSize(90, 36))
        self.pushButton_5.setStyleSheet("\n"
"\n"
"QPushButton { color:rgb(254, 253, 247);\n"
"    border-radius:15px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 76, 0)\n"
"\n"
" }\n"
"\n"
"QPushButton:hover{background-color:#057A3A;color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 5px;\n"
" padding-top:5px;\n"
" \n"
"    background-color: rgb(0, 85QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"} 0);\n"
" \n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Itens"))
        self.pushButton_2.setText(_translate("Form", "Registros"))
        self.pushButton_3.setText(_translate("Form", "Locais"))
        self.cat_item_btn.setText(_translate("Form", "Patrimônio"))
        self.pushButton_4.setText(_translate("Form", "Exportar"))
        self.date_i.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.label.setText(_translate("Form", " Data de Início                             Data Fim"))
        self.date_f.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.pushButton_5.setText(_translate("Form", "Filtrar"))
        self.label_3.setText(_translate("Form", "text_log"))
        self.label_2.setText(_translate("Form", "date_text"))
