# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Documents\GitHub\controle_patrimonio\PATP\bckp\asset_ctrl\templates\interfaces\user_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 592)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hUserCreate = QtWidgets.QFrame(Form)
        self.hUserCreate.setMinimumSize(QtCore.QSize(0, 90))
        self.hUserCreate.setMaximumSize(QtCore.QSize(16777215, 45))
        self.hUserCreate.setStyleSheet("background-color: #057A3A;\n"
"border-radius: 15px;")
        self.hUserCreate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hUserCreate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hUserCreate.setObjectName("hUserCreate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hUserCreate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.hUserCreate)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fotolabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fotolabel.setFont(font)
        self.fotolabel.setStyleSheet("color:white;")
        self.fotolabel.setObjectName("fotolabel")
        self.horizontalLayout_4.addWidget(self.fotolabel, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_back = QtWidgets.QFrame(self.hUserCreate)
        self.frame_back.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_back.setObjectName("frame_back")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_back)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnReturn = QtWidgets.QPushButton(self.frame_back)
        self.btnReturn.setMinimumSize(QtCore.QSize(45, 45))
        self.btnReturn.setMaximumSize(QtCore.QSize(45, 45))
        self.btnReturn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReturn.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btnReturn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/corner-up-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReturn.setIcon(icon)
        self.btnReturn.setIconSize(QtCore.QSize(27, 27))
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout_5.addWidget(self.btnReturn)
        self.horizontalLayout_2.addWidget(self.frame_back, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.hUserCreate)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    height: 30px;\n"
"    border-radius:9px;\n"
"    border:1px solid rgb(134, 138, 131);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_body = QtWidgets.QFrame(self.frame_2)
        self.frame_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_body)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_11 = QtWidgets.QFrame(self.frame_body)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.userLabel = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("color:rgb(5, 122, 58)")
        self.userLabel.setObjectName("userLabel")
        self.verticalLayout_6.addWidget(self.userLabel)
        self.userEdit = QtWidgets.QLineEdit(self.frame_11)
        self.userEdit.setMinimumSize(QtCore.QSize(300, 36))
        self.userEdit.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.userEdit.setFont(font)
        self.userEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.userEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.userEdit.setObjectName("userEdit")
        self.verticalLayout_6.addWidget(self.userEdit)
        self.passLabel = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.passLabel.setFont(font)
        self.passLabel.setStyleSheet("color:rgb(5, 122, 58)")
        self.passLabel.setObjectName("passLabel")
        self.verticalLayout_6.addWidget(self.passLabel)
        self.passEdit = QtWidgets.QLineEdit(self.frame_11)
        self.passEdit.setMinimumSize(QtCore.QSize(300, 36))
        self.passEdit.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.passEdit.setFont(font)
        self.passEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.passEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.passEdit.setObjectName("passEdit")
        self.verticalLayout_6.addWidget(self.passEdit)
        self.horizontalLayout.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_body)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.nameLabel = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color:rgb(5, 122, 58)")
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_7.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.frame_12)
        self.nameEdit.setMinimumSize(QtCore.QSize(300, 36))
        self.nameEdit.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameEdit.setFont(font)
        self.nameEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.nameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_7.addWidget(self.nameEdit)
        self.emailLabel = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.emailLabel.setFont(font)
        self.emailLabel.setStyleSheet("color:rgb(5, 122, 58)")
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_7.addWidget(self.emailLabel)
        self.emailEdit = QtWidgets.QLineEdit(self.frame_12)
        self.emailEdit.setMinimumSize(QtCore.QSize(300, 36))
        self.emailEdit.setMaximumSize(QtCore.QSize(300, 36))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emailEdit.setFont(font)
        self.emailEdit.setStyleSheet("\n"
"QLineEdit{\n"
"background-color:white;    \n"
"border-radius: 5px;\n"
"border: 1px solid #057A3A;\n"
"border-bottom: 3px solid #057A3A;\n"
"\n"
"    border-top-right-radius: 5px;  \n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"")
        self.emailEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.emailEdit.setObjectName("emailEdit")
        self.verticalLayout_7.addWidget(self.emailEdit)
        self.horizontalLayout.addWidget(self.frame_12)
        self.verticalLayout_5.addWidget(self.frame_body)
        self.frame_rodape = QtWidgets.QFrame(self.frame_2)
        self.frame_rodape.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_rodape.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.frame_rodape.setStyleSheet("QPushButton{\n"
"    background-color:white;\n"
"    border-radius:9px;\n"
"    color:black;\n"
"}")
        self.frame_rodape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rodape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rodape.setObjectName("frame_rodape")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_rodape)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_rodape)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cargLabel = QtWidgets.QLabel(self.frame_8)
        self.cargLabel.setMinimumSize(QtCore.QSize(90, 45))
        self.cargLabel.setMaximumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.cargLabel.setFont(font)
        self.cargLabel.setStyleSheet("color:rgb(5, 122, 58)")
        self.cargLabel.setObjectName("cargLabel")
        self.horizontalLayout_6.addWidget(self.cargLabel, 0, QtCore.Qt.AlignRight)
        self.cargoBox = QtWidgets.QComboBox(self.frame_8)
        self.cargoBox.setMinimumSize(QtCore.QSize(200, 27))
        self.cargoBox.setMaximumSize(QtCore.QSize(300, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cargoBox.setFont(font)
        self.cargoBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cargoBox.setStyleSheet("QComboBox{\n"
"background-color : white;\n"
"border:1px solid gray;\n"
"align-itens:center;\n"
"}\n"
"\n"
"\n"
"")
        self.cargoBox.setCurrentText("")
        self.cargoBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.cargoBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cargoBox.setIconSize(QtCore.QSize(12, 12))
        self.cargoBox.setFrame(False)
        self.cargoBox.setModelColumn(0)
        self.cargoBox.setObjectName("cargoBox")
        self.horizontalLayout_6.addWidget(self.cargoBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_btns = QtWidgets.QFrame(self.frame_rodape)
        self.frame_btns.setStyleSheet("")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnClear = QtWidgets.QPushButton(self.frame_btns)
        self.btnClear.setMinimumSize(QtCore.QSize(120, 45))
        self.btnClear.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnClear.setFont(font)
        self.btnClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClear.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid black;\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_8.addWidget(self.btnClear)
        self.btnConfirm = QtWidgets.QPushButton(self.frame_btns)
        self.btnConfirm.setMinimumSize(QtCore.QSize(120, 45))
        self.btnConfirm.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btnConfirm.setFont(font)
        self.btnConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConfirm.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    border: 1px solid black;\n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout_8.addWidget(self.btnConfirm)
        self.horizontalLayout_3.addWidget(self.frame_btns, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_rodape)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_bottom = QtWidgets.QFrame(Form)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_bottom)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.frame_bottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fotolabel.setText(_translate("Form", "TEXT"))
        self.userLabel.setText(_translate("Form", "Usuário:"))
        self.userEdit.setPlaceholderText(_translate("Form", "Usuário utilizado para login"))
        self.passLabel.setText(_translate("Form", "Senha:"))
        self.passEdit.setPlaceholderText(_translate("Form", "Senha do usuário"))
        self.nameLabel.setText(_translate("Form", "Nome:"))
        self.nameEdit.setPlaceholderText(_translate("Form", "Nome do usuário"))
        self.emailLabel.setText(_translate("Form", "Email:"))
        self.emailEdit.setPlaceholderText(_translate("Form", "Email do usuário"))
        self.cargLabel.setText(_translate("Form", "Cargo:"))
        self.btnClear.setText(_translate("Form", "Clear"))
        self.btnConfirm.setText(_translate("Form", "Confirmar"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; -qt-user-state:65536;\"><span style=\" font-size:8pt;\">Lorem ipsum odor amet, consectetuer adipiscing elit. Nullam nec fringilla aliquam urna porttitor? At gravida nunc felis felis eros gravida bibendum nam sodales. Quis tincidunt sem molestie phasellus; sed porttitor. Vulputate felis auctor hac purus velit. Eros ex tristique urna elementum nullam proin montes proin ultricies.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Aliquet torquent tristique felis facilisi magna cras. Ullamcorper ornare tortor ipsum ligula tristique curabitur pulvinar. Vitae dictum tempus habitant eget eu curae. Lectus eu bibendum ullamcorper ultricies parturient malesuada molestie feugiat. Dui taciti facilisi aliquet gravida finibus eros vel sed. Venenatis penatibus ultrices magna per quam neque maximus blandit. Dapibus aenean vivamus; proin condimentum congue gravida eu. Eget elementum leo nunc fermentum laoreet taciti pretium. Penatibus ipsum inceptos a; potenti inceptos lectus consectetur porta. Facilisi id mollis vulputate, parturient potenti maximus mauris.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
import resource_rc
