# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\IP\Documents\GitHub\controle_patrimonio\PATP\bckp\asset_ctrl\templates\interfaces\user_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(995, 555)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_User = QtWidgets.QFrame(Form)
        self.new_User.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_User.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_User.setObjectName("new_User")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.new_User)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout.addWidget(self.new_User)
        self.userFrame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userFrame.setFont(font)
        self.userFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userFrame.setObjectName("userFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.userFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_user_frame = QtWidgets.QFrame(self.userFrame)
        self.header_user_frame.setStyleSheet("background-color:transparent;")
        self.header_user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_user_frame.setObjectName("header_user_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_user_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_frame = QtWidgets.QFrame(self.header_user_frame)
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.search_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3.addWidget(self.search_frame, 0, QtCore.Qt.AlignLeft)
        self.infoFrame = QtWidgets.QFrame(self.header_user_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoFrame.sizePolicy().hasHeightForWidth())
        self.infoFrame.setSizePolicy(sizePolicy)
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.infoFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnDetails = QtWidgets.QPushButton(self.infoFrame)
        self.btnDetails.setMinimumSize(QtCore.QSize(120, 45))
        self.btnDetails.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDetails.setFont(font)
        self.btnDetails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDetails.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetails.setIcon(icon)
        self.btnDetails.setIconSize(QtCore.QSize(27, 27))
        self.btnDetails.setObjectName("btnDetails")
        self.horizontalLayout_7.addWidget(self.btnDetails)
        self.horizontalLayout_3.addWidget(self.infoFrame)
        self.cadFrame = QtWidgets.QFrame(self.header_user_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cadFrame.sizePolicy().hasHeightForWidth())
        self.cadFrame.setSizePolicy(sizePolicy)
        self.cadFrame.setBaseSize(QtCore.QSize(0, 0))
        self.cadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cadFrame.setObjectName("cadFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.cadFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnCad = QtWidgets.QPushButton(self.cadFrame)
        self.btnCad.setMinimumSize(QtCore.QSize(120, 45))
        self.btnCad.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCad.setFont(font)
        self.btnCad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCad.setStyleSheet("QPushButton { \n"
"    background-color: #057A3A;\n"
"     color:rgb(254, 253, 247);\n"
"    border-radius:9px;        \n"
"    padding:8px\n"
" }\n"
"\n"
"QPushButton:hover{background-color:rgb(85, 170, 127);color:white}\n"
"\n"
"QPushButton:pressed{\n"
" padding-left: 2px;\n"
" padding-top:2px;\n"
" \n"
"    background-color: rgb(0, 85, 0);\n"
" \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/user-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCad.setIcon(icon1)
        self.btnCad.setIconSize(QtCore.QSize(27, 27))
        self.btnCad.setObjectName("btnCad")
        self.horizontalLayout_8.addWidget(self.btnCad)
        self.horizontalLayout_3.addWidget(self.cadFrame)
        self.verticalLayout_2.addWidget(self.header_user_frame)
        self.text_Frames = QtWidgets.QFrame(self.userFrame)
        self.text_Frames.setMinimumSize(QtCore.QSize(600, 30))
        self.text_Frames.setMaximumSize(QtCore.QSize(600, 45))
        self.text_Frames.setStyleSheet("background-color: #057A3A;\n"
"    border-top-right-radius: 15px;  \n"
"    border-bottom-right-radius: 15px;")
        self.text_Frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_Frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_Frames.setObjectName("text_Frames")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.text_Frames)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.text_Frames)
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        self.label.setMaximumSize(QtCore.QSize(300, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.text_Frames, 0, QtCore.Qt.AlignLeft)
        self.info_user = QtWidgets.QFrame(self.userFrame)
        self.info_user.setMinimumSize(QtCore.QSize(0, 0))
        self.info_user.setStyleSheet("border-radius:9px;")
        self.info_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_user.setObjectName("info_user")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.info_user)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_user = QtWidgets.QTableView(self.info_user)
        self.l_user.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.l_user.setObjectName("l_user")
        self.horizontalLayout.addWidget(self.l_user)
        self.frame_2 = QtWidgets.QFrame(self.info_user)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color:white;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_6.addWidget(self.textBrowser)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(5, 122, 58)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.logsReg = QtWidgets.QTableView(self.frame_2)
        self.logsReg.setMaximumSize(QtCore.QSize(450, 150))
        self.logsReg.setStyleSheet("background-color:white;    \n"
"border:3px solid #057A3A;\n"
"border-radius:10px\n"
"\n"
"")
        self.logsReg.setObjectName("logsReg")
        self.verticalLayout_6.addWidget(self.logsReg)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.info_user)
        self.verticalLayout.addWidget(self.userFrame)
        self.createFrame = QtWidgets.QFrame(Form)
        self.createFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createFrame.setObjectName("createFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.createFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.createFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnDetails.setText(_translate("Form", "Detalhes"))
        self.btnCad.setText(_translate("Form", "Cadastrar"))
        self.label.setText(_translate("Form", "Usuários cadastrados"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\">Lorem ipsum odor amet, consectetuer adipiscing elit. Aliquet elementum ad ridiculus parturient elit, praesent elit. Blandit lorem quam; nisl venenatis vivamus mus faucibus dapibus integer. Vulputate interdum per facilisis taciti viverra faucibus fringilla? Auctor hendrerit pellentesque sed arcu eros odio egestas lectus. Lacus felis felis bibendum etiam luctus quisque quam at et. Elementum facilisi libero senectus cras donec in. Tempus pharetra finibus nibh nec pulvinar. Finibus taciti tellus urna laoreet habitasse lacinia justo tempus.</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "Quantidade de usuários por cargo:"))
import resource01_rc
